### ISSUE TITLE
hello , I need flutter set to a history  version (for example v1.2.1).  what should I do

### ISSUE THREAD

**Issue by CoderWeiXiao** [passsy/flutter_wrapper#11]
Our team members need  same flutter version, but we don't need the latest.  how to set it ?

**Comment by passsy** [comment]
`flutter_wrapper` makes the flutter sdk a git submodule. Therefore you can use all existing git techniques you want.

This is how you downgrade to `v1.2.1`
```bash
$ cd .flutter
$ git checkout v1.2.1
$ cd ..
$ git add .flutter
$ git commit -m "Downgrade Flutter to v1.2.1"
```
