### ISSUE TITLE
Is this project discontinued

### ISSUE THREAD

**Issue by bottee** [passsy/flutter_wrapper#21]
Is this project still actively maintained?

**Comment by dalewking** [comment]
It is definitely a shame this project never caught on. I personally found that using it in Android Studio was a hassle.

**Comment by passsy** [comment]
*if it ain't broke, don't fix it*
I'm still using `flutterw` in all my projects. While I experienced some minor annoyances, it always has worked and still works.

The past months I was a bit scared shipping releases to `flutterw`. People were using it in very different setups and critical projects and the last thing I wanted was accidentally breaking it. It [happened](https://github.com/passsy/flutter_wrapper/commit/4e6e2c9cd41d3fe1d598f3e6b2153ab1fe56d13d) in the past so I was cautious.

I really wanted tests, but writing tests for bash scripts is hard, if not impossible. After many different attempts, I now found a [way](https://github.com/passsy/flutter_wrapper/tree/master/test) to do it and feel confident improving it further

The latest [v1.2.0](https://github.com/passsy/flutter_wrapper/releases/tag/v1.2.0) release contains all fixes reported in the last year

**Comment by dalewking** [comment]
Is it just me or did Jetbrains silently add some automatic support for this project? If I open a project in Android Studio that has flutterw in it I am noticing that the flutter SDK path is already set to the .flutter directory for the project.

**Comment by dalewking** [comment]
I also discovered there is now fvm which is basically this project on steroids https://fvm.app/
