### ISSUE TITLE
What about running in CI?

### ISSUE THREAD

**Issue by romanr** [passsy/flutter_wrapper#36]
Do you have to insert curl command in your CI? Anyone uses this with CI, es there an example? 
Maybe it can be made into a Github action?

**Comment by passsy** [comment]
Hey!

Using flutterw on CI is very easy. It was the main goal of this project.

Just call it, an it will download flutter for you. I added an example to the readme https://github.com/passsy/flutter_wrapper#using-flutterw-on-ci

On bare-bone machines, you might have to install additional tooling. I created docker containers for this to build your Flutter app on linux. There's also an android version to build the android version. https://github.com/passsy/docker-flutterw
