### ISSUE TITLE
Hello friend I need to use this so badly but ran into this

### ISSUE THREAD

**Issue by Isonomic** [passsy/flutter_wrapper#5]
I am using vscode and windows sadly. 

C:\ProdigyNetwork\Flutter\udemy_scoped_model>curl -sL https://raw.githubusercontent.com/passsy/flutter_wrapper/master/install.sh | bash -
Error: Not a git repository, to fix this run: git init

Any thoughts ? And sorry in advance if this is a silly question

**Comment by passsy** [comment]
As the error mentions your flutter project is not a git repository. You have to initialize git first.

```
> git init
```
