### ISSUE TITLE
installation - git url out of date ?

### ISSUE THREAD

**Issue by biancashouse** [passsy/flutter_wrapper#8]
If I follow your command line instructions, I get a message that the url does not lead to the git repo containing your wrapper.

I have cloned the project directly using git clone... fingers crossed it'll work for me, because flutter just upgraded past 1.0 and it's dependency hell !

Thanks for this.

**Comment by passsy** [comment]
Can you give me more details of the error message? I double checked all urls and everything seems to be ok. It works perfectly on macOS and Linux.

**Comment by biancashouse** [comment]
My mistake. Apologies. Does work on my old macbook after all.
